apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.broker_certs_name }}

spec:
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}

  refreshInterval: {{ .Values.secretStore.refreshInterval }}

  target:
    name: {{ .Values.broker_certs_name }}
    creationPolicy: {{ .Values.secretStore.creationPolicy }}
    deletionPolicy: {{ .Values.secretStore.deletionPolicy }}

    template:
      data:
        .ca.cert.pem: {{ printf "{{ .%s }}" "ca_cert" | quote }}
        .broker.cert.pem: {{ printf "{{ .%s }}" "broker_cert" | quote }}
        .broker.key-pk8.pem: {{ printf "{{ .%s }}" "broker_key" | quote }}

  data:
    - secretKey: "ca_cert"
      remoteRef:
        key: "messaging-pulsar-ca-cert"
    - secretKey: "broker_cert"
      remoteRef:
        key: "messaging-pulsar-broker-cert"
    - secretKey: "broker_key"
      remoteRef:
        key: "messaging-pulsar-broker-key"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.client_certs_name }}

spec:
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}

  refreshInterval: {{ .Values.secretStore.refreshInterval }}

  target:
    name: {{ .Values.client_certs_name }}
    creationPolicy: {{ .Values.secretStore.creationPolicy }}
    deletionPolicy: {{ .Values.secretStore.deletionPolicy }}

    template:
      data:
        .ca.cert.pem: {{ printf "{{ .%s }}" "ca_cert" | quote }}
        .client.cert.pem: {{ printf "{{ .%s }}" "client_cert" | quote }}
        .client.key-pk8.pem: {{ printf "{{ .%s }}" "client_key" | quote }}

  data:
    - secretKey: "ca_cert"
      remoteRef:
        key: "messaging-pulsar-ca-cert"
    - secretKey: "client_cert"
      remoteRef:
        key: "messaging-pulsar-client-cert"
    - secretKey: "client_key"
      remoteRef:
        key: "messaging-pulsar-client-key"
